const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{PlayersLives: 0},
	{Bananas: 0},
	{Solid: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Ground: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{SnailMove: 0},
	{Enemy: 0},
	{RedBox: 0},
	{Tree: 0},
	{Pin: 0},
	{Lives: 0},
	{Banana: 0},
	{BananaCounter: 0},
	{bananaIcon: 0},
	{Bullet: 0},
	{hantu: 0},
	{TiledBackground2: 0},
	{Touch: 0},
	{Audio: 0},
	{Sprite: 0},
	{Gameover: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Enemy: class extends self.ISpriteInstance {},
	RedBox: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Lives: class extends self.ISpriteInstance {},
	Banana: class extends self.ISpriteInstance {},
	BananaCounter: class extends self.ITextInstance {},
	bananaIcon: class extends self.ISpriteInstance {},
	hantu: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {}
}